version: '3.2'

services:
  master:
    image: ire7715/yarn-spark:${VERSION}
    ports:
      - "50070:50070"
      - "8088:8088"
      - "50075:50075"
      - "18080:18080"
    environment:
      - NODE_TYPE=master
    tty: true
    networks:
      - yarn_network
    volumes:
      - type: volume
        source: master_data
        target: /data

  slave-1:
    image: ire7715/yarn-spark:${VERSION}
    environment:
      - NODE_TYPE=slave
    tty: true
    networks:
      - yarn_network
    volumes:
      - type: volume
        source: slave_1_data
        target: /data

  slave-2:
    image: ire7715/yarn-spark:${VERSION}
    environment:
      - NODE_TYPE=slave
    tty: true
    networks:
      - yarn_network
    volumes:
      - type: volume
        source: slave_2_data
        target: /data

  driver:
    image: ire7715/yarn-spark:${VERSION}
    tty: true
    networks:
      - yarn_network

volumes:
  master_data:
  slave_1_data:
  slave_2_data:

networks:
  yarn_network:
    driver: "bridge"
